# Generated by Django 3.2.13 on 2022-07-14 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_collectionsvglist_is_coll'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='is_coll',
            field=models.IntegerField(default=1),
        ),
    ]
