# Generated by Django 3.2.13 on 2022-07-13 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svg', '0002_svg_pure_svg'),
    ]

    operations = [
        migrations.AddField(
            model_name='svgpackage',
            name='pure_svg_package',
            field=models.BooleanField(default=False),
        ),
    ]
