# Generated by Django 3.2.13 on 2022-07-14 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svg', '0003_svgpackage_pure_svg_package'),
    ]

    operations = [
        migrations.AlterField(
            model_name='svg',
            name='svg_name',
            field=models.CharField(max_length=64),
        ),
    ]
