# Generated by Django 3.2.13 on 2022-07-13 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('svg', '0002_svg_pure_svg'),
        ('like', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeCountRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('range_count', models.IntegerField(default=0)),
                ('created_data', models.DateTimeField(auto_now_add=True)),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='svg.svgpackage')),
            ],
            options={
                'ordering': ('-range_count',),
            },
        ),
    ]
